### ISSUE TITLE
ReferenceError occued in index.js

### ISSUE THREAD

**Issue by wnaldj1589TW** [lunchboxer/graphql-subscriptions-client#12]
At first, thank you for sharing graphql subscription library :)
Sadly, there is a small error while using `graphql-subscriptions-client.`

When I use `graphql-subscriptions-client`, I met the ReferenceError just like belo.
```
ReferenceError: WebSocket is not defined
           at new SubscriptionClient (/home/user/bdd-test/node_modules/graphql-subscriptions-client/dist/index.js:21:19)
```
Currently, it is temporarily solved by adding `var WebSocket = require("ws")` at the top of the index.js.
Do you have another approach to resolve this error?

**Comment by lunchboxer** [comment]
If Websocket is not defined then it sounds like you are using this on the server side. It's designed to function in the browser, but sometimes bundlers can get things mixed up,  but I personally haven't had any such problems in a very long time, so don't remember. Can you tell me more about the environment and the application you are using it in?

More directly to answer your question, it depends. If you aren't in the browser then you should import package 'ws' as you suggest, but if you want it to work in both then use 'isomorphic-ws'.

**Comment by wnaldj1589TW** [comment]
Yeah, I'm not using it in the browser.
I'm using `graphql-subscriptions-client` in the test code for the graphql server.
So I need to import package in the `node_modules/graphql-subscriptions-client/dist/index.js`,
if I want to use `graphql-subscriptions-client` in server.
Is this what you meant?

Thank you for your answer!

**Comment by lunchboxer** [comment]
I see. That makes sense, but I haven't done such things myself. I would fork it, then link the forked repo to your project where you are doing the testing, add in the ws module and see how that goes for you. It's typescript so it would be `import Websocket from 'ws'` at the top of `/src/index.ts`. Then you'll need to rebuild : `npm run build`. isomorphic-ws does exist, but I'm not sure how that would effect the rest of the use-cases. I've never used it, but their documentation does mention that it's not a perfect replica of the native browser Websocket api.

**Comment by wnaldj1589TW** [comment]
Thanks a lot! It makes clear :)
Do you have a plan to resolve this issue?

**Comment by lunchboxer** [comment]
I am a little concerned that making it usable in node could interfere with use in the browser. I've made a branch `isomorphic-ws` which I believe should fix it, but I haven't had time to run through it and see if it works.

**Comment by lunchboxer** [comment]
What testing library are you using?

**Comment by wnaldj1589TW** [comment]
I'm using it with cucumber-js to apply BDD style.
This is the dependency of the test cases in package.json.
```
   "dependencies": {
     "@babel/node": "^7.12.10",
     "@babel/polyfill": "^7.12.1",
     "@types/ws": "^7.4.0",
     "chai": "^4.2.0",
     "chai-as-promised": "^7.1.1",
     "graphql": "^15.5.0",
     "graphql-request": "^3.4.0",
     "graphql-subscriptions-client": "^0.16.0",
     "isomorphic-ws": "^4.0.1",
     "q": "^1.5.1",
     "ws": "^7.4.2"
   }
```

**Comment by dzhelezov** [comment]
As a workaround, one may declare `WebSocket` globally like this:

```
declare global {
  var WebSocket: typeof WebSocket
}

globalThis.WebSocket = require('ws')
```

**Comment by YuriFontella** [comment]
Hi, I also had this same problem on the client side, in the browser. I understand that the package is standalone, but the documentation doesn't say anything about installing the websocket. As said, in the browser it is not necessary.

![image](https://user-images.githubusercontent.com/4920619/121792518-394c4a00-cbcc-11eb-8346-0683a0174ef6.png)

My graphql/subscription server is working.

![image](https://user-images.githubusercontent.com/4920619/121792528-639e0780-cbcc-11eb-82b9-bee0802f6b09.png)

Or am I doing something wrong?

**Comment by YuriFontella** [comment]
Sorry, as I'm using react this should start inside useEffect. Worked perfectly.
