### ISSUE TITLE
Headers?

### ISSUE THREAD

**Issue by richcorbs** [lunchboxer/graphql-subscriptions-client#24]
Thanks for this. Been looking for a way to do graphql subscriptions without apollo.

Is this the right way to include headers?

```
const client = new SubscriptionClient(GRAPHQL_ENDPOINT, {
  reconnect: true,
  lazy: true, // only connect when there is a query
  connectionCallback: (error) => {
    error && console.error(error);
  },
  headers: {
    'x-auth-token': 'my-auth-token'
  }
})
```

**Comment by richcorbs** [comment]
Looks like this uses the native WebSocket implementation and as such it doesn't support sending headers. I wonder how subscriptions-transport-ws does it.

**Comment by richcorbs** [comment]
Found it! `connectionParams` FTW! Thanks for this project!

**Comment by enes-get-local** [comment]
> Found it! `connectionParams` FTW! Thanks for this project!

@richcorbs Hey, i m using `connectionParams` but i can't see it in headers. Can you share your code block if it works ?
