### ISSUE TITLE
Trying with Apollo, error

### ISSUE THREAD

**Issue by frederikhors** [lunchboxer/graphql-subscriptions-client#3]
Maybe you can do something for this.

I'm both querying with STRING and GQL query. Both way I got this error in browser.

```log
Uncaught Invariant Violation: Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? http://docs.apollostack.com/apollo-client/core.html#gql
    at new InvariantError 
```

**Comment by lunchboxer** [comment]
Yeah I don't think that there is much point in using this with apollo-client. apollo-client and WebSocketLink can be used with rollup and maybe my previous rollup problems are simply with an older version. I don't use apollo-client and I think that if you do there won't be any advantage from using this library. The fact that it doesn't work either should decide that matter for us. I've edited the readme accordingly.
