### ISSUE TITLE
Issues on 0.14.0

### ISSUE THREAD

**Issue by onhate** [lunchboxer/graphql-subscriptions-client#8]
This change commit directly to master without a PR (which made pretty hard to find the reason why it was done) is causing applications to fail with the error `Right-hand side of 'instanceof' is not object`.

As per `ws` docs https://www.npmjs.com/package/ws

> Note: This module does not work in the browser. The client in the docs is a reference to a back end with the role of a client in the WebSocket communication. Browser clients must use the native WebSocket object. To make the same code work seamlessly on Node.js and the browser, you can use one of the many wrappers available on npm, like isomorphic-ws.

https://github.com/lunchboxer/graphql-subscriptions-client/commit/aa7873df0ceed67d94e9f4b1a890c9d87e30e330#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R2

![image](https://user-images.githubusercontent.com/980905/97713879-4f335180-1ab8-11eb-81ea-368a1b765123.png)
![image](https://user-images.githubusercontent.com/980905/97714069-9883a100-1ab8-11eb-8766-9f1498fa9a13.png)

I happens when it tries to open the connection and instantiate a new Websocket object, it does not happens on 0.13.0 only on 0.14.0

**Comment by lunchboxer** [comment]
Since this library is used by others now, I'll try to use a more systematic workflow and avoid publishing packages that don't work. Thank you for sorting this.
